package com.application.projectarchitecture.api;

public enum APIType {
    SIGN_IN,
    FOOD_LIST_USER,
    FOOD_LIST_VENDOR,
    PAYMENT,
    USER_ORDER_LIST,
    FOOD_DELETE,
    REQUEST_ORDER_LIST,
    FOOD_EDIT,
    ORDER_CANCEL,
    ORDER_ACCEPT,
    ORDER_COMPLETE,
    ADD_PHOTO,
    ADD_FOOD,
    UPDATE_FOOD,
    TRANSACTION_LIST,
    ORDER_DETAIL,
    USER_PROFILE,
    FORGOT_API,
    VENDOR_LIST
}
